name       = "awsprepai-progress"
main       = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding     = "DB"
database_name = "awsprepai-progress"
database_id   = "9cf683ca-f6f6-4eeb-91f2-900e5e2f2128"

[vars]
RSA_PUBLIC_KEY_B64 = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtZEVxU09iZy9OeWVmdWxHVW4yVgpnUVNMajU3Wk4wMDBqell2WFUwR1lyelJmQW9sUmoxdzl6dldhcTBYOFNqNzhmS3N5RnpaOVlJSzFsWWVzK1Y4Cm5UVHp6ZDhnZk5kbTlIQk9pbjRacytXK1poU05pTlZDOHhoT25zdkU4cHRlVWlIcWNWOGRiOW1paDRyenJHSzcKamUzdkgzTTg1Sm12RVN4MkQ0QmtsbmxqdXJ5L2NnREdwVHZmYjFwRHJINkNSOVg0RDIvQUJnd21sNUg4SGpVRwpYNXl0RG1aWjh5cGYyZW00WW9mNFpYTThLVmxMZE95TWhhNDdyN3I0L3JlTkQvbysvakp0MUJOU3h2UFk1VlROCkJGOVVEU3RsTnQ2dXgzS1djWUlGa0Y1N3B2UERUV0ZlTXpDak5Ca3FJTEV3Rkl0RHRDWCtLRWVEZ0dnaGhOa0kKOFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
